export let available = [
  {
    name: "Yoga & Meditation Course",
    date: "Tuesday",
    slotsAvailable: 30,
    slotsFree: 16,
    booked: true,
    time: "10:30 - 11:45",
    location: "Deck A2",
    type: "event",
    icon: "yoga.svg",
    id: 0,
  },
  {
    name: "Beach Volleyball Training",
    date: "Tuesday",
    slotsAvailable: 16,
    slotsFree: 3,
    booked: true,
    time: "10:30 - 11:45",
    location: "Deck A4",
    type: "event",
    icon: "volleyball.svg",
    id: 1,
  },
  {
    name: "Barcelona City Tour",
    date: "Tuesday",
    slotsAvailable: 60,
    slotsFree: 9,
    booked: true,
    time: "13:30 - 17:00",
    location: "Gate B2",
    type: "event",
    icon: "tour.svg",
    id: 4,
  },
  {
    name: "Fitness Course",
    date: "Tuesday",
    slotsAvailable: 50,
    slotsFree: 29,
    booked: false,
    time: "09:30 - 10:30",
    location: "Room 411",
    type: "event",
    icon: "bicep.svg",
    id: 10,
  },
];
